name: assets_gen_new
description: >
  The assets_gen_new package helps you to generate a .dart file that contains all assets according to `pubspec.yaml`.
version: 1.5.5
repository: https://github.com/zhoudajun-ola/assets_gen

environment:
  sdk: ^3.6.0

dependencies:
  ansicolor: ">=2.0.0 <3.0.0"
  args: ">=2.0.0 <3.0.0"
  build: ">=2.0.0 <5.0.0"
  dart_style: ">=2.0.0 <4.0.0"
  glob: ">=2.0.0 <3.0.0"
  logging: ">=1.0.0 <2.0.0"
  path: ">=1.8.0 <2.0.0"
  watcher: ">=1.0.0 <2.0.0"
  yaml: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ">=4.0.0 <7.0.0"